*
* This file was auto-generated by Lazarus. time.struct_time(tm_year=2026, tm_mon=5, tm_mday=27, tm_hour=9, tm_min=19, tm_sec=19, tm_wday=2, tm_yday=147, tm_isdst=1)
*
* For more information about the parameters in this file,
* please consult the official PAML documenation.
*
seqfile = reformatted_alignment.phy
treefile = reformatted_tree.tre
outfile = out.paml
noisy = 3
verbose = 9
runmode = 0
seqtype = 2
aaRatefile = model.dat
model = 3
fix_alpha = 0
alpha = 1.0
ncatG = 4
RateAncestor = 2
Small_Diff = 1.0e-6
cleandata = 0
method = 1
fix_blength = 2
